In [15]:
import numpy as np

In [ ]:
#2.  Write a NumPy program to reverse an array (first element becomes last).
#Original array:
#[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
#Reverse array:
#[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [11]:
a = np.arange(12,38)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [14]:
np.flip(np.arange(12,38))

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [30]:
b = np.arange(2,11)
print(b)

[ 2  3  4  5  6  7  8  9 10]


In [31]:
b.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [33]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
#Expected Output:
#[[ 2 3 4]
#[ 5 6 7]
#[ 8 9 10]]
